#!/usr/bin/env R

pca=read.table("merge.mds", header=T, as.is=T)
status=read.table("merge.txt", header=T, as.is=T)
pcastat=merge(pca, status, by.x="IID", all.x=T)
plot(pcastat[,4], pcastat[,5], xlab="PC1", ylab="PC2", type="n")
for(i in 1:nrow(pcastat)){
 if(pcastat[i,6]=="ACB") points(pcastat[1,4], pcastat[i,5], col="2")
 if(pcastat[i,6]=="ASW") points(pcastat[1,4], pcastat[i,5], col="3")
 if(pcastat[i,6]=="BEB") points(pcastat[1,4], pcastat[i,5], col="4")
 if(pcastat[i,6]=="CDX") points(pcastat[1,4], pcastat[i,5], col="5")
 if(pcastat[i,6]=="CEU") points(pcastat[1,4], pcastat[i,5], col="6")
 if(pcastat[i,6]=="CHB") points(pcastat[1,4], pcastat[i,5], col="7")
 if(pcastat[i,6]=="CHS") points(pcastat[1,4], pcastat[i,5], col="8")
 if(pcastat[i,6]=="CLM") points(pcastat[1,4], pcastat[i,5], col="9")
 if(pcastat[i,6]=="ESN") points(pcastat[1,4], pcastat[i,5], col="10")
 if(pcastat[i,6]=="FIN") points(pcastat[1,4], pcastat[i,5], col="11")
 if(pcastat[i,6]=="GBR") points(pcastat[1,4], pcastat[i,5], col="12")
 if(pcastat[i,6]=="GIH") points(pcastat[1,4], pcastat[i,5], col="13")
 if(pcastat[i,6]=="GWD") points(pcastat[1,4], pcastat[i,5], col="14")
 if(pcastat[i,6]=="IBS") points(pcastat[1,4], pcastat[i,5], col="15")
 if(pcastat[i,6]=="ITU") points(pcastat[1,4], pcastat[i,5], col="16")
 if(pcastat[i,6]=="JPT") points(pcastat[1,4], pcastat[i,5], col="17")
 if(pcastat[i,6]=="KHV") points(pcastat[1,4], pcastat[i,5], col="18")
 if(pcastat[i,6]=="LWK") points(pcastat[1,4], pcastat[i,5], col="19")
 if(pcastat[i,6]=="MSL") points(pcastat[1,4], pcastat[i,5], col="20")
 if(pcastat[i,6]=="MXL") points(pcastat[1,4], pcastat[i,5], col="21")
 if(pcastat[i,6]=="PEL") points(pcastat[1,4], pcastat[i,5], col="22")
 if(pcastat[i,6]=="PJL") points(pcastat[1,4], pcastat[i,5], col="23")
 if(pcastat[i,6]=="PUR") points(pcastat[1,4], pcastat[i,5], col="24")
 if(pcastat[i,6]=="STU") points(pcastat[1,4], pcastat[i,5], col="25")
 if(pcastat[i,6]=="TSI") points(pcastat[1,4], pcastat[i,5], col="26")
 if(pcastat[i,6]=="YRI") points(pcastat[1,4], pcastat[i,5], col="27")
 if(pcastat[i,6]=="CASE") points(pcastat[1,4], pcastat[i,5], col="28", pch=19)
 if(pcastat[i,6]=="CONTROL") points(pcastat[1,4], pcastat[i,5], col="29", pch=19)
 }
identify(pcastat[,4], pcastat[,5], labels=pcastat[,2])
