#!/usr/bin/env R

pca=read.table("merge.mds", header=T, as.is=T)
status=read.table("merge.txt", header=T, as.is=T)
pcastat=merge(pca, status, by.x="IID", all.x=T)

png("mds-plot.png", res=1200, height=5, width=5, units="in")
par(mfrow=c(1,1))
plot(pcastat[,4], pcastat[,5], xlab="PC1", ylab="PC2", type="n")
for(i in 1:nrow(pcastat)){
 if(pcastat[i,6]=='ACB') points(pcastat[i,4], pcastat[i,5], col=2, pch=19)
 if(pcastat[i,6]=='ASW') points(pcastat[i,4], pcastat[i,5], col=3, pch=19)
 if(pcastat[i,6]=='BEB') points(pcastat[i,4], pcastat[i,5], col=4, pch=19)
 if(pcastat[i,6]=='CDX') points(pcastat[i,4], pcastat[i,5], col=5, pch=19)
 if(pcastat[i,6]=='CEU') points(pcastat[i,4], pcastat[i,5], col=6, pch=19)
 if(pcastat[i,6]=='CHB') points(pcastat[i,4], pcastat[i,5], col=7, pch=19)
 if(pcastat[i,6]=='CHS') points(pcastat[i,4], pcastat[i,5], col=8, pch=19)
 if(pcastat[i,6]=='CLM') points(pcastat[i,4], pcastat[i,5], col=9, pch=19)
 if(pcastat[i,6]=='ESN') points(pcastat[i,4], pcastat[i,5], col=10, pch=19)
 if(pcastat[i,6]=='FIN') points(pcastat[i,4], pcastat[i,5], col=11, pch=19)
 if(pcastat[i,6]=='GBR') points(pcastat[i,4], pcastat[i,5], col=12, pch=19)
 if(pcastat[i,6]=='GIH') points(pcastat[i,4], pcastat[i,5], col=13, pch=19)
 if(pcastat[i,6]=='GWD') points(pcastat[i,4], pcastat[i,5], col=14, pch=19)
 if(pcastat[i,6]=='IBS') points(pcastat[i,4], pcastat[i,5], col=15, pch=19)
 if(pcastat[i,6]=='ITU') points(pcastat[i,4], pcastat[i,5], col=16, pch=19)
 if(pcastat[i,6]=='JPT') points(pcastat[i,4], pcastat[i,5], col=17, pch=19)
 if(pcastat[i,6]=='KHV') points(pcastat[i,4], pcastat[i,5], col=18, pch=19)
 if(pcastat[i,6]=='LWK') points(pcastat[i,4], pcastat[i,5], col=19, pch=19)
 if(pcastat[i,6]=='MSL') points(pcastat[i,4], pcastat[i,5], col=20, pch=19)
 if(pcastat[i,6]=='MXL') points(pcastat[i,4], pcastat[i,5], col=21, pch=19)
 if(pcastat[i,6]=='PEL') points(pcastat[i,4], pcastat[i,5], col=22, pch=19)
 if(pcastat[i,6]=='PJL') points(pcastat[i,4], pcastat[i,5], col=23, pch=19)
 if(pcastat[i,6]=='PUR') points(pcastat[i,4], pcastat[i,5], col=24, pch=19)
 if(pcastat[i,6]=='STU') points(pcastat[i,4], pcastat[i,5], col=25, pch=19)
 if(pcastat[i,6]=='TSI') points(pcastat[i,4], pcastat[i,5], col=26, pch=19)
 if(pcastat[i,6]=='YRI') points(pcastat[i,4], pcastat[i,5], col=27, pch=19)
 if(pcastat[i,6]=='CASE') points(pcastat[i,4], pcastat[i,5], col=1, pch=19)
 if(pcastat[i,6]=='CONTROL') points(pcastat[i,4], pcastat[i,5], col=1, pch=19)
 }
legend("bottom", c("ACB","ASW","BEB","CDX","CEU","CHB","CLM","ESN","FIN","GBR","GIH","GWD","IBS","ITU","JPT","KHV","LWK","MSL","MXL","PEL","PJL","PUR","STU","TSI","YRI","CASECON"), pch = 19, col = c(2, 3, 4, 1), horiz=TRUE)
dev.off()
#identify(pcastat[,4], pcastat[,5], labels=pcastat[,2])


png("mds-plot.png", res=1200, height=5, width=5, units="in")
par(mfrow=c(1,1))
plot(pcastat[,4], pcastat[,5], xlab="PC1", ylab="PC2", type="n")
for(i in 1:nrow(pcastat)){
if(pcastat[i,6]=='CEU') points(pcastat[i,4], pcastat[i,5], col=2, pch=19)
if(pcastat[i,6]=='YRI') points(pcastat[i,4], pcastat[i,5], col=3, pch=19)
if(pcastat[i,6]=='CAJ') points(pcastat[i,4], pcastat[i,5], col=4, pch=19)
if(pcastat[i,6]=='CASE') points(pcastat[i,4], pcastat[i,5], col=1, pch=19)
if(pcastat[i,6]=='CONTROL') points(pcastat[i,4], pcastat[i,5], col=1, pch=19)
}
legend("bottom", c("CEU", "YRI", "CAJ", "CASECON"), pch = 19, col = c(2, 3, 4, 1))
dev.off()
